Test if before_deploy can fail a build

diff --git a/conda.recipe/deploy b/conda.recipe/deploy
--- a/conda.recipe/deploy
+++ b/conda.recipe/deploy
@@ -3,6 +3,9 @@
 set -e # exit on error
 set -x # echo commands
 
+# Test if before_deploy makes fail
+exit 1
+
 if  [[ -z "${TRAVIS_TAG}" ]]; then
     echo
     echo "SKIPPING DEPLOY STAGE SCRIPT --- This is a NOT build for a release tag"
